language: java

sudo: false

env:
  global:
    - secure: ZfeJ/ibm4vQyWgpmQuFjZjEy/uiT9FcjC+D0kTDRukT3u4YfUwYEDdAcMeSp2YBis6y+ek3q2jrpjIVn7QcPwd5PY497DZd2f7IPPiz3Nt/kT+BrzerzyL/9Iw7zaCphxhDUSMbprDFT4JnZMNFkAW6TnKz86KDWEFXAVj25ulzfpsNcsCH4Z7TMEbpkJatgaCc5JFHW83ahGtQoZ7+JoS6yt1Kt5zdB8Jtz97denV5DQqLoYXmKXEu21RK6n34XO2QFCTBf1UOEM1wC3xrD11tNMQTlgeqGgXZWul9HtksQ9RTxcy5Z0ePwc3akMF095iOmnjtE7F/eC32AeOPmfycqskGTS/Xh7/602LEwoosPxsAoPe9dKlQPnQBOjuZ35ZtDxV8f9VM59WW5lKH0zaOC5+6zLYnOAwg/Djy4UQ2WupdOHlb3kB2zxK5VUEioD4P7WBjnr2G15rv8McxJV5GOrbTgDzcj8qTGLhsNvSJlFUNIFM/ZbA6hiBOD8bJF5vz2YbU6p/ekcbNFI9cppXwVbk3Rx1xAoxlmHivUZMzBzd2g+hcecRZdQAU4H5/uxF/s3JQHTKCOXiPizYZDYVST4CCOcTtThuSock5Vb4H6PWO30hqNTyN2e+BQ/qoyVoHfXkjjU4NRvMxkE1VIxI+e2NkUTimzbzbAoz5jl9w=

addons:
  apt_packages:
    - gcc
    - g++
    - gcc-multilib
    - g++-multilib
    - binutils-mingw-w64-i686
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - lib32z1

install:
  - if [ `uname -m` = x86_64 ]; then wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin -O ndk.bin; fi
  - chmod a+x ndk.bin
  - ./ndk.bin -y | grep -v Extracting
  - export NDK_HOME=`pwd`/android-ndk-r10d
  - rm -rf libs || exit 0
  - cd jni

script:
  - ant -f build-linux32.xml -Dhas-compiler=true
  - ant -f build-linux64.xml -Dhas-compiler=true
  - ant -f build-windows32.xml -Dhas-compiler=true
  - ant -f build-windows64.xml -Dhas-compiler=true
  - ant -f build-android32.xml -Dhas-ndk-build=true
  - cd ../libs && ls -LR && cd ../

after_script:
  - git config --global user.email "${GIT_NAME}"
  - git config --global user.name "${GIT_EMAIL}"
  - git config --global push.default matching
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git remote set-url origin https://github.com/non2d/non.natives.git
  - git add libs/
  - git commit -m "Built natives"
  - git push