language: java
sudo: false
addons:
  apt_packages:
  - gcc
  - g++
  - gcc-multilib
  - g++-multilib
  - binutils-mingw-w64-i686
  - binutils-mingw-w64-x86-64
  - gcc-mingw-w64-i686
  - g++-mingw-w64-i686
  - gcc-mingw-w64-x86-64
  - g++-mingw-w64-x86-64
  - lib32z1
install:
- if [ `uname -m` = x86_64 ]; then wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin -O ndk.bin; fi
- chmod a+x ndk.bin
- "./ndk.bin -y | grep -v Extracting"
- export NDK_HOME=`pwd`/android-ndk-r10d
script:
- ant compile-linux -Dhas-compiler=true
- ant compile-windows -Dhas-compiler=true
- ant compile-android -Dhas-compiler=true
- ant compile-library
- ant pack-linux
- ant pack-windows
- ant pack-android
- ant pack-library
after_success:
- git config --global user.email "${GIT_EMAIL}"
- git config --global user.name "Thomas Slusny"
- git config --global push.default matching
- echo -e "machine github.com\n  login ${GIT_LOGIN}\n  password ${GIT_PASSWORD}" >> ~/.netrc
- git add bin/
- git status -s
- git commit -m "Travis CI build [ci skip]"
- git branch tmp
- git checkout experimental
- git merge tmp
- git branch -d tmp
- git push https://github.com/nondev/nonlua.git experimental
env:
  global:
    secure: BqUInZSR0eojCkAq9D8ABOBSS3wm6f78UVdN3F7WKlMX2ngv3XAedoJubWjsZ7/CIF7NdQalEmwn7OG5SaTuHb91V/w/sWVlp/7BEYDrPZFWZgDsd4gwQL0ZRawoZIZ7Lej890ZmgfiD1/3kLSHaqkc8hcBlRA5N1MCIAY4NWoL0imwyE8eS0hFgnClKeMBwEAgbQOxxCo5kBKgmGbX++NHa0RPIIMbZLlAoSsvVIubt25GUb2IgVE4J9MFeAnNiYVF+c67lXBTOvgpvJXHN2HQMFCMaFtxpad4PRnqL8mDigHNCDbJ/+NVUtyikAS4NWqV/v64ADF/c0ySkOSaOgETOpZImMvCZk79p1x+p6x/R6PF+vMPakj5pi4wz34Lx88/WClMgpMuZpKPUe2vuriU+9c0BYNyTr/XG8FXTPOe7pQl32JojZ8oy7A9wzaSWEhyzeJtAALoefFkSsJC6WnmjqmxuzcPtJmYUj4hJe8dTePUCbEh/bcA4jP5QzvoPYeY31y3krT1xtT63m6jZuA+LKWH/Sj/4RBAE+Tszj05rbSCixoyRT09xqo/T3cD19+EDOPAvVL44kk1S2PcyCZi+Dsrmk7sLZTHpR/GYpheqqsMeMvCyiZ+jdlANSqezqEzw8Fc7r6TDoPkXSr4195xt0Z2oGGAA5WY1xOiv0zI=